### ISSUE TITLE
[AVM Module Issue]: Tags variable not working

### ISSUE THREAD

**Issue by brmcsorley** [Azure/terraform-azurerm-avm-res-azurestackhci-virtualmachineinstance#13]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

Adding tags = var.tags when referencing module does not work.  TF files in AVM module for resource creation are missing a tags variable.

hybrid_compute_machine, nic, and domain_join resources are affected.

 
module "vm" {
  source  = "Azure/avm-res-azurestackhci-virtualmachineinstance/azurerm"
  version = "0.1.1"
  [other variables here]
  **tags                  = var.tags**
}

**Comment by JonAtWork7** [comment]
I am also having this issue.  Tags are declared but never used.  This is causing issues for us because we have several tagging policies.  Can this be fixed?

**Comment by xhy8759** [comment]
@brmcsorley thanks for opening the issue, it's fixed. @JonAtWork7
