### ISSUE TITLE
[AVM Module Issue]: Domain Join Extension changes not ignored

### ISSUE THREAD

**Issue by JonAtWork7** [Azure/terraform-azurerm-avm-res-azurestackhci-virtualmachineinstance#21]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2

### Description

After deploying a VM using this AVM, subsequent underlying changes (automatic updates) to properties of the domain_join extension are not ignored.  I believe that the same lifecycle ignore_changes might need to be applied via to this resource as well.

  ~ resource "azapi_resource" "domain_join" {
      ~ body                      = {
          ~ properties = {
              ~ autoUpgradeMinorVersion = false -> true
              ~ typeHandlerVersion      = "1.3.11" -> "1.3"

**Comment by xhy8759** [comment]
Hi @JonAtWork7, thanks for opening the issue.
It should haven been resolved.

**Comment by JonAtWork7** [comment]
@xhy8759 Thanks!  Working great now!
