### ISSUE TITLE
[AVM Module Issue]: Dynamic Memory logic problem

### ISSUE THREAD

**Issue by JonAtWork7** [Azure/terraform-azurerm-avm-res-azurestackhci-virtualmachineinstance#22]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2

### Description

After deploying a VM using this AVM, subsequent terraform plan/apply runs show an issue with dynamic memory.  It looks like the logic might be backwards or misconfigured, because it continually wants to set dynamic memory to NULL if it is set to True.  If it's set to false, it then wants to configure the min/max memory.

 ~ resource "azapi_resource" "virtual_machine" {
      ~ body                      = {
          ~ properties       = {
              ~ hardwareProfile = {
                  ~ dynamicMemoryConfig = {
                      - maximumMemoryMB    = null
                      - minimumMemoryMB    = null
                      - targetMemoryBuffer = null
                    } -> null

**Comment by xhy8759** [comment]
Hi @JonAtWork7, thanks for opening the issue.
It should haven been resolved.
