### ISSUE TITLE
[AVM Module Issue]: dataDisks parameter is not working

### ISSUE THREAD

**Issue by JonAtWork7** [Azure/terraform-azurerm-avm-res-azurestackhci-virtualmachineinstance#33]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.4

### Description

The newly added support for data disks does not seem to be working.  The AVM seems to be treating azapi_resource.data_disks as an array and it is trying to access it using numeric indices.  

When adding a VM with a data disk, it errors out with:

Error: Invalid index

  on .terraform/modules/rdctst_vms_test.tst-demo-gh-04.vm/locals.tf line 63, in locals:
  63:         id = azapi_resource.data_disks[i].id
    ├────────────────
    │ azapi_resource.data_disks is object with 1 attribute "disk1"

The given key does not identify an element in this collection value. An
object only supports looking up attributes by name, not by numeric index.

Instead, I believe you need to treat data_disks as an object with named attributes and iterate over each key-value pair to access the id attribute.  Hoping you can fix this quickly since we need to deploy VMs with data disks.  Thanks.

**Comment by xhy8759** [comment]
Related PR: #37

**Comment by brmcsorley** [comment]
Thank you.  I can now add disks via Terraform, but now have two new related issues.

In the disks.tf:

There needs to be a variable for adding tags.

And the containerID property needs to be ignored.

![Image](https://github.com/user-attachments/assets/7cec5f91-0d2f-43b9-a17f-c20f2c9c0215)

**Comment by xhy8759** [comment]
> Thank you. I can now add disks via Terraform, but now have two new related issues.
> 
> In the disks.tf:
> 
> There needs to be a variable for adding tags.
> 
> And the containerID property needs to be ignored.
> 
> ![Image](https://github.com/user-attachments/assets/7cec5f91-0d2f-43b9-a17f-c20f2c9c0215)

Hi, this is the related PR #41 which was merged.

**Comment by JonAtWork7** [comment]
Confirmed this is fixed.
