### ISSUE TITLE
[AVM Module Issue]:  Schema Validation Failed

### ISSUE THREAD

**Issue by brmcsorley** [Azure/terraform-azurerm-avm-res-azurestackhci-virtualmachineinstance#36]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.4.1

### Description

When trying to deploy another VM via this AVM, TF complains about the schema of previously deployed VM's.

![Image](https://github.com/user-attachments/assets/3b3ef510-0058-4522-8c77-133b79079a0e)

Need to add body.properties.cloudMetadata.provider to ignore_changes in main.tf for the hybrid computer resource.

**Comment by xhy8759** [comment]
Related PR: #38

**Comment by xhy8759** [comment]
Thanks for creating the issue, @brmcsorley I've merged PR to resolve this.
